export type ThemeModuleLoader = () => Promise<Record<string, unknown>>;

export const siteThemeModuleLoaders: Record<string, ThemeModuleLoader> = {
  "components/ArticleList.tsx": () => import("../../frontend-library/botanical-editorial/components/ArticleList"),
  "components/EditorialArticleCard.tsx": () => import("../../frontend-library/botanical-editorial/components/EditorialArticleCard"),
  "components/FeaturedGrid.tsx": () => import("../../frontend-library/botanical-editorial/components/FeaturedGrid"),
  "components/FooterAccordionSection.tsx": () => import("../../frontend-library/botanical-editorial/components/FooterAccordionSection"),
  "components/HomeCategoryCard.tsx": () => import("../../frontend-library/botanical-editorial/components/HomeCategoryCard"),
  "components/HomeCategoryGrid.tsx": () => import("../../frontend-library/botanical-editorial/components/HomeCategoryGrid"),
  "components/HomeSectionHeading.tsx": () => import("../../frontend-library/botanical-editorial/components/HomeSectionHeading"),
  "components/LatestArticlesGrid.tsx": () => import("../../frontend-library/botanical-editorial/components/LatestArticlesGrid"),
  "components/Pagination.tsx": () => import("../../frontend-library/botanical-editorial/components/Pagination"),
  "layouts/ArchivePageLayout.tsx": () => import("../../frontend-library/botanical-editorial/layouts/ArchivePageLayout"),
  "layouts/ArticlePageLayout.tsx": () => import("../../frontend-library/botanical-editorial/layouts/ArticlePageLayout"),
  "layouts/CategoryPageLayout.tsx": () => import("../../frontend-library/botanical-editorial/layouts/CategoryPageLayout"),
  "layouts/GlobalPageShell.tsx": () => import("../../frontend-library/botanical-editorial/layouts/GlobalPageShell"),
  "layouts/HomepageLayout.tsx": () => import("../../frontend-library/botanical-editorial/layouts/HomepageLayout"),
  "layouts/SearchPageLayout.tsx": () => import("../../frontend-library/botanical-editorial/layouts/SearchPageLayout"),
  "layouts/StaticPageLayout.tsx": () => import("../../frontend-library/botanical-editorial/layouts/StaticPageLayout"),
  "sections/ArticleHero.tsx": () => import("../../frontend-library/botanical-editorial/sections/ArticleHero"),
  "sections/CategoryHero.tsx": () => import("../../frontend-library/botanical-editorial/sections/CategoryHero"),
  "sections/CategoryShowcaseSection.tsx": () => import("../../frontend-library/botanical-editorial/sections/CategoryShowcaseSection"),
  "sections/FeaturedArticlesSection.tsx": () => import("../../frontend-library/botanical-editorial/sections/FeaturedArticlesSection"),
  "sections/HomeHero.tsx": () => import("../../frontend-library/botanical-editorial/sections/HomeHero"),
  "sections/LatestArticlesSection.tsx": () => import("../../frontend-library/botanical-editorial/sections/LatestArticlesSection"),
  "sections/NewsletterBlock.tsx": () => import("../../frontend-library/botanical-editorial/sections/NewsletterBlock"),
  "sections/RelatedArticlesSection.tsx": () => import("../../frontend-library/botanical-editorial/sections/RelatedArticlesSection"),
  "shell/FooterShell.tsx": () => import("../../frontend-library/botanical-editorial/shell/FooterShell"),
  "shell/HeaderShell.tsx": () => import("../../frontend-library/botanical-editorial/shell/HeaderShell"),
  "shell/SearchPanelShell.tsx": () => import("../../frontend-library/botanical-editorial/shell/SearchPanelShell"),
  "shell/SidebarShell.tsx": () => import("../../frontend-library/botanical-editorial/shell/SidebarShell"),
};
